###############################################################
#
#  This configures the robot to work with MoveIt Pro
#
###############################################################

based_on_package: "motiv_xlink_hw_config"

# Baseline hardware configuration parameters for MoveIt Pro.
hardware:
  # Parameters used to configure the robot description through XACRO.
  robot_description:
    urdf:
      package: "atomos_xlink_hw_config"
      path: "description/motiv_xlink_atomos.mock.urdf" #Using manual urdf for control over xlink position w.r.t. servicer sled.


# Configuration for loading behaviors and objectives.
objectives:
  behavior_loader_plugins:
    calibration:
      - "calibration_behaviors::CalibrationBehaviorsLoader"
  objective_library_paths:
    custom_objectives:
      package_name: "atomos_xlink_hw_config"
      relative_path: "objectives"
  # Specify location of the waypoints file.
  waypoints_file:
    package_name: "atomos_xlink_hw_config"
    relative_path: "waypoints/waypoints.yaml"